# Generated by Django 2.0 on 2019-11-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atelieriia', '0003_auto_20191112_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='binaire',
        ),
    ]
