membres_bureau =[
		{'nom':'Bathiebo',
		'prenom':'Richard',
		'poste':'Président du club Atelier iia',
		'description':' Duis aute irure dolor in reprehenderit in voluptate velit ereprehenderit in voluptate velit esse',
		'image':'richard.jpg',
		'lien_facebook':'facebook.com',
		'lien_twitter':'twitter.com',
		'lien_linkdin':'linkdin.com'
		},

		{'nom':'Meye',
		'prenom':'Jean Yannick',
		'poste':'Responsable pédagogique',
		'description':' Duis aute irure dolor in reprehenderit in voluptate velit ereprehenderit in voluptate velit esse',
		'image':'yannick.jpg',
		'lien_facebook':'facebook.com',
		'lien_twitter':'twitter.com',
		'lien_linkdin':'linkdin.com'
		},
		{'nom':'Sow',
		'prenom':'Rokhaya',
		'poste':'Commission pédagogique',
		'description':' Duis aute irure dolor in reprehenderit in voluptate velit ereprehenderit in voluptate velit esse',
		'image':'rokhi.jpg',
		'lien_facebook':'facebook.com',
		'lien_twitter':'twitter.com',
		'lien_linkdin':'linkdin.com'
		},
		{'nom':'Aw',
		'prenom':'Alassane',
		'poste':'Commission organisation',
		'description':' Duis aute irure dolor in reprehenderit in voluptate velit ereprehenderit in voluptate velit esse',
		'image':'aw.jpg',
		'lien_facebook':'facebook.com',
		'lien_twitter':'twitter.com',
		'lien_linkdin':'linkdin.com'
		},
		{'nom':'Aw',
		'prenom':'Alassane',
		'poste':'Commission organisation',
		'description':' Duis aute irure dolor in reprehenderit in voluptate velit ereprehenderit in voluptate velit esse',
		'image':'aw.jpg',
		'lien_facebook':'facebook.com',
		'lien_twitter':'twitter.com',
		'lien_linkdin':'linkdin.com'
		},
		{'nom':'Aw',
		'prenom':'Alassane',
		'poste':'Commission organisation',
		'description':' Duis aute irure dolor in reprehenderit in voluptate velit ereprehenderit in voluptate velit esse',
		'image':'aw.jpg',
		'lien_facebook':'facebook.com',
		'lien_twitter':'twitter.com',
		'lien_linkdin':'linkdin.com'
		},
		{'nom':'Aw',
		'prenom':'Alassane',
		'poste':'Commission organisation',
		'description':' Duis aute irure dolor in reprehenderit in voluptate velit ereprehenderit in voluptate velit esse',
		'image':'aw.jpg',
		'lien_facebook':'facebook.com',
		'lien_twitter':'twitter.com',
		'lien_linkdin':'linkdin.com'
		},
	]